[global.databases]
shotlog = { url = "postgres://localhost/kraken_development" }

[development]
secret_key = "FrCdWp/BVo7kGa/j1RTWzefx3ZRKg1CL5tjKBgetLyU="
log = "normal"

[production]
secret_key = "MZwvNoCYiIO7rnd8hTMTnA2VuoW1mEiieO8iZWJqgCI="
